# Use postgres/example user/password credentials
# docker swarm init
# docker stack deploy -c stack.yml stack
# psql -h localhost -U postgres -d postgres
# adminer: http://swarm-ip:8080, http://localhost:8080, or http://host-ip:8080
# strapi: http://localhost:1337
# docker service ls
# docker service ps stack_db
# docker container ls -q
# docker stack rm stack
# docker swarm leave --force
version: "3"

services:
  # db1:
  #   image: postgres:11.1-alpine
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 100M
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     webnet:
  #       aliases:
  #         - host
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: "a"
  #     POSTGRES_PASSWORD: "a"
  #     POSTGRES_DB: "a"
  #   volumes:
  #     - ./initdb:/docker-entrypoint-initdb.d/
  #     - ./datadb:/var/lib/postgresql/data

  # adminer:
  #   image: adminer
  #   deploy:
  #     replicas: 1
  #     resources:
  #       limits:
  #         cpus: "0.1"
  #         memory: 100M
  #     restart_policy:
  #       condition: on-failure
  #   networks:
  #     - webnet
  #   ports:
  #     - 8080:8080

  strapi:
    image: salsa_api
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - w1
    ports:
      - "1337:1337"
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=db
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_SSL=false
      - DATABASE_AUTHENTICATION_DATABASE=strapi
      - HOST=localhost
      # - APP_NAME=strapi-app
      # - DATABASE_CLIENT=postgres
      # - DATABASE_HOST=host
      # - DATABASE_PORT=5432
      # - DATABASE_NAME=strapi
      # - DATABASE_USERNAME=a
      # - DATABASE_PASSWORD=a
      # - DATABASE_SSL=false
      # - DATABASE_AUTHENTICATION_DATABASE=strapi
      # - HOST=localhost
    volumes:
      - ./strapi-app:/usr/src/api/strapi-app
      # - /usr/src/api/strapi-app/node_modules
  db:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=strapi
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    networks:
      - w1
    volumes:
      - ./db:/data/db

networks:
  w1:
    external: true
    name: host
#  driver: overlay
#  attachable: true
